nav:
    - Home: index.md
    - Recursion: recursion
    - Algorithm-design-paradigm: Algorithm-design-paradigm
    - Analysis-of-algorithms: Analysis-of-algorithms
    - Algorithm-and-math: Algorithm-and-math.md
    - Application: Application